//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BMI", Namespace="http://schemas.datacontract.org/2004/07/SoapService")]
    [System.SerializableAttribute()]
    public partial class BMI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Bmi {
            get {
                return this.BmiField;
            }
            set {
                if ((this.BmiField.Equals(value) != true)) {
                    this.BmiField = value;
                    this.RaisePropertyChanged("Bmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] More {
            get {
                return this.MoreField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreField, value) != true)) {
                    this.MoreField = value;
                    this.RaisePropertyChanged("More");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Risk {
            get {
                return this.RiskField;
            }
            set {
                if ((object.ReferenceEquals(this.RiskField, value) != true)) {
                    this.RiskField = value;
                    this.RaisePropertyChanged("Risk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBmiSoapService")]
    public interface IBmiSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBmiSoapService/myBMI", ReplyAction="http://tempuri.org/IBmiSoapService/myBMIResponse")]
        double myBMI(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBmiSoapService/myBMI", ReplyAction="http://tempuri.org/IBmiSoapService/myBMIResponse")]
        System.Threading.Tasks.Task<double> myBMIAsync(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBmiSoapService/myHealth", ReplyAction="http://tempuri.org/IBmiSoapService/myHealthResponse")]
        WebClient.ServiceReference1.BMI myHealth(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBmiSoapService/myHealth", ReplyAction="http://tempuri.org/IBmiSoapService/myHealthResponse")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.BMI> myHealthAsync(int height, int weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBmiSoapServiceChannel : WebClient.ServiceReference1.IBmiSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BmiSoapServiceClient : System.ServiceModel.ClientBase<WebClient.ServiceReference1.IBmiSoapService>, WebClient.ServiceReference1.IBmiSoapService {
        
        public BmiSoapServiceClient() {
        }
        
        public BmiSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BmiSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BmiSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double myBMI(int height, int weight) {
            return base.Channel.myBMI(height, weight);
        }
        
        public System.Threading.Tasks.Task<double> myBMIAsync(int height, int weight) {
            return base.Channel.myBMIAsync(height, weight);
        }
        
        public WebClient.ServiceReference1.BMI myHealth(int height, int weight) {
            return base.Channel.myHealth(height, weight);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.BMI> myHealthAsync(int height, int weight) {
            return base.Channel.myHealthAsync(height, weight);
        }
    }
}
